"use client";
import { useEffect, useMemo, useState } from "react";
import { Card, Deck, FlashyData, Rating, Scheduling, initialData } from "@/lib/domain";
import { schedule } from "@/lib/scheduler";

const storageKey = "flashy-data-v1";
const uid = () => crypto.randomUUID();
const today = () => new Date().toLocaleDateString("en-CA");
const labels: Record<Rating, [string, string]> = { AGAIN: ["Again", "مرة أخرى"], HARD: ["Hard", "صعب"], GOOD: ["Good", "جيد"], EASY: ["Easy", "سهل"] };
const stateLabels: Record<string, string> = { NEW: "جديدة", LEARNING: "تعلّم", REVIEW: "مراجعة", RELEARNING: "إعادة تعلّم" };

function dueCards(data: FlashyData, deckId?: string) {
  const now = Date.now();
  return data.cards.filter(c => !c.suspended && (!deckId || c.deckId === deckId) && !data.decks.find(d => d.id === c.deckId)?.archived)
    .map(card => ({ card, schedule: data.scheduling.find(s => s.cardId === card.id)! }))
    .filter(x => new Date(x.schedule.dueAt).getTime() <= now)
    .sort((a, b) => { const rank: Record<string, number> = { REVIEW: 0, RELEARNING: 0, LEARNING: 1, NEW: 2 }; return rank[a.schedule.state] - rank[b.schedule.state] || new Date(a.schedule.dueAt).getTime() - new Date(b.schedule.dueAt).getTime(); });
}
function dir(lang?: string, value?: string) { return lang === "ar" || (!lang && /[\u0600-\u06FF]/.test(value || "")) ? "rtl" : "ltr"; }

export default function Flashy() {
  const [data, setData] = useState<FlashyData>(initialData); const [ready, setReady] = useState(false);
  const [view, setView] = useState<"home" | "decks" | "stats" | "settings" | "study">("home");
  const [deckFilter, setDeckFilter] = useState<string | undefined>(); const [queue, setQueue] = useState<{card: Card; schedule: Scheduling}[]>([]);
  const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false); const [started, setStarted] = useState(0); const [sessionStarted, setSessionStarted] = useState(0);
  const [showDeckForm, setShowDeckForm] = useState(false); const [showCardForm, setShowCardForm] = useState<string | null>(null); const [showCustomPicker, setShowCustomPicker] = useState(false);
  useEffect(() => { const saved = localStorage.getItem(storageKey); if (saved) try { setData(JSON.parse(saved)); } catch {} setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem(storageKey, JSON.stringify(data)); }, [data, ready]);
  const due = useMemo(() => dueCards(data), [data]);
  const todayReviews = data.reviews.filter(r => r.reviewedAt.slice(0, 10) === today());
  const retention = data.reviews.length ? Math.round(data.reviews.filter(r => r.wasCorrect).length / data.reviews.length * 100) : 0;
  const startStudy = (deckId?: string, cardIds?: string[]) => { const q = cardIds ? cardIds.map(cardId => { const card = data.cards.find(c => c.id === cardId); const schedule = data.scheduling.find(s => s.cardId === cardId); return card && schedule ? { card, schedule } : null; }).filter((item): item is { card: Card; schedule: Scheduling } => item !== null) : dueCards(data, deckId); const now = Date.now(); setDeckFilter(deckId); setQueue(q); setIndex(0); setRevealed(false); setStarted(now); setSessionStarted(now); setView("study"); };
  const submit = (rating: Rating) => {
    const item = queue[index]; if (!item || !revealed) return; const now = new Date(); const result = schedule({ now, rating, ...item.schedule });
    const attemptId = uid();
    setData(prev => ({ ...prev, scheduling: prev.scheduling.map(s => s.cardId === item.card.id ? { ...s, ...result, reviewCount: s.reviewCount + 1, lastReviewedAt: now.toISOString() } : s), reviews: [...prev.reviews, { id: attemptId, cardId: item.card.id, deckId: item.card.deckId, rating, wasCorrect: rating !== "AGAIN", responseTimeMs: Date.now() - started, previousState: item.schedule.state, nextState: result.state, reviewedAt: now.toISOString() }] }));
    setIndex(i => i + 1); setRevealed(false); setStarted(Date.now());
  };
  const moveCard = (direction: -1 | 1) => {
    setIndex(current => Math.max(0, Math.min(queue.length - 1, current + direction)));
    setRevealed(false);
    setStarted(Date.now());
  };
  useEffect(() => { const key = (e: KeyboardEvent) => { const tag = (e.target as HTMLElement)?.tagName; if (tag === "INPUT" || tag === "TEXTAREA") return; if (view !== "study") return; if (e.code === "ArrowLeft") { e.preventDefault(); moveCard(-1); return; } if (e.code === "ArrowRight") { e.preventDefault(); moveCard(1); return; } if (e.code === "Space") { e.preventDefault(); setRevealed(true); } const rating = ({ "1": "AGAIN", "2": "HARD", "3": "GOOD", "4": "EASY" } as Record<string, Rating>)[e.key]; if (rating) submit(rating); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); });
  const addDeck = (form: FormData) => { const title = String(form.get("title") || "").trim(); if (!title) return; const deck: Deck = { id: uid(), title, description: String(form.get("description") || ""), color: String(form.get("color") || "cyan"), icon: "✦", createdAt: new Date().toISOString() }; setData(d => ({ ...d, decks: [deck, ...d.decks] })); setShowDeckForm(false); };
  const addCard = (form: FormData) => { const front = String(form.get("front") || "").trim(), back = String(form.get("back") || "").trim(); if (!front || !back || !showCardForm) return; const card: Card = { id: uid(), deckId: showCardForm, type: String(form.get("type")) as Card["type"], front, back, hint: String(form.get("hint") || ""), example: String(form.get("example") || ""), frontLanguage: String(form.get("frontLanguage") || ""), backLanguage: String(form.get("backLanguage") || ""), createdAt: new Date().toISOString() }; const scheduling: Scheduling = { cardId: card.id, state: "NEW", dueAt: new Date().toISOString(), intervalDays: 0, stepIndex: 0, easeFactor: 2.5, reviewCount: 0, lapseCount: 0, correctStreak: 0 }; setData(d => ({ ...d, cards: [...d.cards, card], scheduling: [...d.scheduling, scheduling] })); setShowCardForm(null); };
  if (!ready) return <main className="boot">Preparing your learning space…</main>;
  const activeCard = queue[index];
  if (view === "study") return <main className="study-shell"><button className="text-btn close" onClick={() => setView("home")}>← إنهاء الجلسة</button>{activeCard ? <section className="study"><div className="study-meta"><span>{deckFilter ? data.decks.find(d => d.id === deckFilter)?.title : "Daily review"}</span><span>{index + 1} / {queue.length}</span></div><div className="study-navigation"><button onClick={() => moveCard(-1)} disabled={index === 0} aria-label="Previous card">← <span>Previous</span><kbd>←</kbd></button><button onClick={() => moveCard(1)} disabled={index >= queue.length - 1} aria-label="Next card"><kbd>→</kbd><span>Next</span> →</button></div><article className={`flashcard ${revealed ? "is-revealed" : ""}`}><p className="eyebrow">{revealed ? "ANSWER" : "QUESTION"}</p><div className="card-copy" dir={dir(revealed ? activeCard.card.backLanguage : activeCard.card.frontLanguage, revealed ? activeCard.card.back : activeCard.card.front)}>{revealed ? activeCard.card.back : activeCard.card.front}</div>{revealed && activeCard.card.example && <p className="example" dir={dir(activeCard.card.backLanguage, activeCard.card.example)}>“{activeCard.card.example}”</p>}</article>{!revealed ? <button className="reveal" onClick={() => setRevealed(true)}>Show answer <kbd>Space</kbd></button> : <div className="ratings">{(["AGAIN", "HARD", "GOOD", "EASY"] as Rating[]).map((r, i) => <button key={r} className={`rate ${r.toLowerCase()}`} onClick={() => submit(r)}><kbd>{i + 1}</kbd><span>{labels[r][data.locale === "ar" ? 1 : 0]}</span></button>)}</div>}</section> : <section className="complete"><span className="spark">✦</span><p className="eyebrow">SESSION COMPLETE</p><h1>Great work.</h1><p>راجعت {queue.length} بطاقات في {Math.max(1, Math.round((Date.now() - sessionStarted) / 60000))} دقائق.</p><button className="reveal" onClick={() => setView("home")}>العودة إلى لوحة التحكم</button></section>}</main>;
  return <main className="app"><aside><div className="brand"><span>✦</span> flashy</div><nav>{[["home","⌂","الرئيسية"],["decks","▤","المجموعات"],["stats","◔","الإحصائيات"],["settings","⚙","الإعدادات"]].map(([id, icon, text]) => <button key={id} className={view === id ? "active" : ""} onClick={() => setView(id as typeof view)}><i>{icon}</i>{text}</button>)}</nav><div className="sidebar-bottom"><div className="avatar">E</div><div><b>El Dawy</b><small>Personal learner</small></div></div></aside><div className="mobile-nav"><button onClick={() => setView("home")}>⌂</button><button onClick={() => setView("decks")}>▤</button><button onClick={() => startStudy()}>▶</button><button onClick={() => setView("stats")}>◔</button></div><section className="content">{view === "home" && <Dashboard data={data} due={due.length} reviewed={todayReviews.length} retention={retention} onStudy={() => startStudy()} onDeck={startStudy} onDecks={() => setView("decks")} />}{view === "decks" && <Decks data={data} setData={setData} onStudy={startStudy} onNew={() => setShowDeckForm(true)} onCard={setShowCardForm} onCustom={() => setShowCustomPicker(true)} />}{view === "stats" && <Stats data={data} />}{view === "settings" && <Settings data={data} setData={setData} />}</section>{showDeckForm && <Modal title="مجموعة جديدة" onClose={() => setShowDeckForm(false)}><form action={addDeck}><label>اسم المجموعة<input name="title" autoFocus maxLength={120} placeholder="مثلاً: تصميم واجهات"/></label><label>وصف اختياري<textarea name="description" maxLength={1000}/></label><label>لون الواجهة<select name="color"><option value="cyan">Cyan</option><option value="violet">Violet</option><option value="lime">Lime</option></select></label><button className="reveal">إنشاء المجموعة</button></form></Modal>}{showCustomPicker && <CustomStudyPicker data={data} onClose={() => setShowCustomPicker(false)} onStart={ids => { setShowCustomPicker(false); startStudy(undefined, ids); }} />}{showCardForm && <Modal title="بطاقة جديدة" onClose={() => setShowCardForm(null)}><form action={addCard}><label>النوع<select name="type"><option value="BASIC">سؤال وإجابة</option><option value="LANGUAGE">لغة ومفردات</option></select></label><label>الواجهة<textarea name="front" required autoFocus maxLength={5000}/></label><label>الإجابة<textarea name="back" required maxLength={10000}/></label><div className="pair"><label>لغة الواجهة<select name="frontLanguage"><option value="ar">العربية</option><option value="en">English</option></select></label><label>لغة الإجابة<select name="backLanguage"><option value="ar">العربية</option><option value="en">English</option></select></label></div><label>مثال اختياري<textarea name="example"/></label><button className="reveal">إضافة البطاقة</button></form></Modal>}</main>;
}

function Dashboard({ data, due, reviewed, retention, onStudy, onDeck, onDecks }: { data: FlashyData; due: number; reviewed: number; retention: number; onStudy: () => void; onDeck: (id: string) => void; onDecks: () => void }) {
  const cardsFor = (id: string) => data.cards.filter(c => c.deckId === id && !c.suspended);
  const dueFor = (id: string) => dueCards(data, id).length;
  return <><header className="topbar"><div><p className="eyebrow">THURSDAY, SEPTEMBER 3</p><h1>صباح الخير، Eldawy <span>✦</span></h1><p className="sub">خطوة صغيرة اليوم، ذاكرة أقوى غدًا.</p></div><button className="icon-btn">⌕</button></header><section className="hero"><div><p className="eyebrow">TODAY'S FOCUS</p><h2>{due ? <>لديك <em>{due} بطاقات</em> مستحقة للمراجعة.</> : <>أنت متقدم على جدولك. <em>أحسنت!</em></>}</h2><p>جلسة قصيرة الآن تحافظ على سلسلة تعلّمك.</p><button className="reveal" onClick={onStudy}>ابدأ المراجعة <span>←</span></button></div><div className="orbit"><span>✦</span><i></i><b>{due}</b><small>due</small></div></section><section className="metrics"><Metric value={due} label="مستحق اليوم" tone="lime"/><Metric value={`${reviewed}/${data.dailyGoal}`} label="تقدم الهدف اليومي" tone="cyan"/><Metric value={`${retention}%`} label="الاحتفاظ الكلي" tone="violet"/><Metric value={streak(data)} label="سلسلة الأيام" tone="orange"/></section><section className="section-head"><div><p className="eyebrow">YOUR DECKS</p><h2>مجموعاتك النشطة</h2></div><button className="text-btn" onClick={onDecks}>عرض الكل ←</button></section><section className="deck-grid">{data.decks.filter(d => !d.archived).map(deck => { const cards = cardsFor(deck.id); const mastered = cards.filter(c => { const s = data.scheduling.find(x => x.cardId === c.id); return s?.state === "REVIEW" && s.intervalDays >= 21; }).length; return <article className="deck" key={deck.id}><div className={`deck-icon ${deck.color}`}>{deck.icon}</div><button className="deck-more">•••</button><h3>{deck.title}</h3><p>{deck.description}</p><div className="deck-foot"><span><b>{dueFor(deck.id)}</b> مستحق</span><span>{cards.length} بطاقة</span></div><div className="progress"><i style={{ width: `${cards.length ? mastered / cards.length * 100 : 0}%` }} /></div><button className="study-mini" onClick={() => onDeck(deck.id)}>Study now <span>→</span></button></article>; })}</section></>;
}
function Metric({ value, label, tone }: { value: string | number; label: string; tone: string }) { return <article className={`metric ${tone}`}><span className="metric-dot"></span><b>{value}</b><p>{label}</p></article>; }
function Decks({ data, setData, onStudy, onNew, onCard, onCustom }: { data: FlashyData; setData: React.Dispatch<React.SetStateAction<FlashyData>>; onStudy: (id: string) => void; onNew: () => void; onCard: (id: string) => void; onCustom: () => void }) { const [query, setQuery] = useState(""); const [layout, setLayout] = useState<"grid" | "table">("grid"); const visible = data.decks.filter(d => !d.archived && d.title.toLowerCase().includes(query.toLowerCase())); const archive = (deck: Deck) => confirm(`أرشفة ${deck.title}؟`) && setData(d => ({ ...d, decks: d.decks.map(x => x.id === deck.id ? { ...x, archived: true } : x) })); const actions = (deck: Deck) => <div className="card-actions"><button onClick={() => onStudy(deck.id)}>ابدأ الدراسة</button><button onClick={() => onCard(deck.id)}>+ بطاقة</button><button className="danger" onClick={() => archive(deck)}>أرشفة</button></div>; return <><header className="topbar"><div><p className="eyebrow">LIBRARY</p><h1>مجموعات البطاقات</h1><p className="sub">نظّم ما تريد أن تتذكره.</p></div><div className="header-actions"><button className="outline-btn" onClick={onCustom}>◫ جلسة مخصصة</button><button className="reveal small" onClick={onNew}>+ مجموعة جديدة</button></div></header><div className="toolbar"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="ابحث في المجموعات…"/><span>{visible.length} مجموعات</span><div className="layout-toggle" aria-label="طريقة العرض"><button className={layout === "grid" ? "active" : ""} onClick={() => setLayout("grid")} aria-label="عرض البطاقات">▦</button><button className={layout === "table" ? "active" : ""} onClick={() => setLayout("table")} aria-label="عرض الجدول">☷</button></div></div>{layout === "grid" ? <section className="deck-grid library">{visible.map(deck => <article className="deck" key={deck.id}><div className={`deck-icon ${deck.color}`}>{deck.icon}</div><h3>{deck.title}</h3><p>{deck.description || "بدون وصف"}</p><div className="deck-foot"><span><b>{dueCards(data, deck.id).length}</b> مستحق</span><span>{data.cards.filter(c => c.deckId === deck.id).length} بطاقة</span></div>{actions(deck)}</article>)}</section> : <section className="deck-table" aria-label="جدول المجموعات"><div className="deck-table-head"><span>المجموعة</span><span>البطاقات</span><span>مستحق</span><span>إجراءات</span></div>{visible.map(deck => <article className="deck-table-row" key={deck.id}><div className="table-deck"><span className={`deck-icon ${deck.color}`}>{deck.icon}</span><div><b>{deck.title}</b><small>{deck.description || "بدون وصف"}</small></div></div><span>{data.cards.filter(c => c.deckId === deck.id).length}</span><span className="due-cell">{dueCards(data, deck.id).length}</span>{actions(deck)}</article>)}</section>}</> }
function Stats({ data }: { data: FlashyData }) { const ratings: Rating[] = ["AGAIN", "HARD", "GOOD", "EASY"]; const max = Math.max(1, ...ratings.map(r => data.reviews.filter(x => x.rating === r).length)); return <><header className="topbar"><div><p className="eyebrow">INSIGHTS</p><h1>تقدّمك في التعلّم</h1><p className="sub">مبني على سجل المراجعات الفعلي.</p></div></header><section className="metrics stats-metrics"><Metric value={data.reviews.filter(r => r.reviewedAt.slice(0, 10) === today()).length} label="مراجعات اليوم" tone="cyan"/><Metric value={`${data.reviews.length ? Math.round(data.reviews.filter(r => r.wasCorrect).length / data.reviews.length * 100) : 0}%`} label="الاحتفاظ (30 يومًا)" tone="violet"/><Metric value={streak(data)} label="سلسلة حالية" tone="orange"/><Metric value={data.scheduling.filter(s => s.state === "REVIEW" && s.intervalDays >= 21).length} label="بطاقات متقنة" tone="lime"/></section><section className="chart-card"><div><p className="eyebrow">RATING DISTRIBUTION</p><h2>كيف تقيّم ذاكرتك</h2></div><div className="bars">{ratings.map(r => { const count = data.reviews.filter(x => x.rating === r).length; return <div key={r}><span>{labels[r][1]}</span><i><b className={r.toLowerCase()} style={{ width: `${count / max * 100}%` }} /></i><strong>{count}</strong></div>})}</div></section><section className="section-head"><div><p className="eyebrow">BY DECK</p><h2>أداء المجموعات</h2></div></section><div className="table">{data.decks.filter(d => !d.archived).map(d => { const cards = data.cards.filter(c => c.deckId === d.id); const reviews = data.reviews.filter(r => r.deckId === d.id); return <div key={d.id}><b>{d.title}</b><span>{cards.length} بطاقات</span><span>{dueCards(data, d.id).length} مستحق</span><span>{reviews.length ? Math.round(reviews.filter(r => r.wasCorrect).length / reviews.length * 100) : 0}% احتفاظ</span></div>})}</div></> }
function Settings({ data, setData }: { data: FlashyData; setData: React.Dispatch<React.SetStateAction<FlashyData>> }) { return <><header className="topbar"><div><p className="eyebrow">PREFERENCES</p><h1>إعدادات التعلّم</h1><p className="sub">اضبط الإيقاع بما يناسبك.</p></div></header><section className="settings-card"><label>الهدف اليومي <span>عدد البطاقات الفريدة التي تراجعها يوميًا.</span><input type="number" min="1" max="500" value={data.dailyGoal} onChange={e => setData(d => ({ ...d, dailyGoal: Math.max(1, Math.min(500, +e.target.value)) }))}/></label><label>لغة الواجهة <span>يمكن للبطاقات نفسها استخدام اتجاه مختلف.</span><select value={data.locale} onChange={e => setData(d => ({ ...d, locale: e.target.value as "ar" | "en" }))}><option value="ar">العربية</option><option value="en">English</option></select></label><label>المنطقة الزمنية <span>تُحسب المواعيد اليومية حسب منطقتك.</span><input value="Africa/Cairo" readOnly /></label></section><button className="text-btn reset" onClick={() => confirm("إعادة بيانات العرض التجريبية؟") && (localStorage.removeItem(storageKey), setData(initialData))}>إعادة ضبط بيانات العرض</button></> }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-label={title}><button className="modal-close" onClick={onClose}>×</button><h2>{title}</h2>{children}</section></div> }
function CustomStudyPicker({ data, onClose, onStart }: { data: FlashyData; onClose: () => void; onStart: (ids: string[]) => void }) {
  const [selected, setSelected] = useState<string[]>([]);
  const activeDecks = data.decks.filter(deck => !deck.archived);
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(cardId => cardId !== id) : [...current, id]);
  const toggleDeck = (deckId: string) => { const ids = data.cards.filter(card => card.deckId === deckId && !card.suspended).map(card => card.id); const allSelected = ids.every(id => selected.includes(id)); setSelected(current => allSelected ? current.filter(id => !ids.includes(id)) : [...new Set([...current, ...ids])]); };
  return <Modal title="جلسة دراسة مخصصة" onClose={onClose}><p className="picker-intro">اختر أي بطاقات من مجموعات مختلفة. ستظهر في قائمة دراسة واحدة، حتى لو لم تكن مستحقة الآن.</p><div className="selection-count"><span>{selected.length} بطاقة مختارة</span><button type="button" onClick={() => setSelected([])} disabled={!selected.length}>إلغاء التحديد</button></div><div className="card-picker">{activeDecks.map(deck => { const cards = data.cards.filter(card => card.deckId === deck.id && !card.suspended); if (!cards.length) return null; const allSelected = cards.every(card => selected.includes(card.id)); return <section key={deck.id}><header><div><span className={`deck-icon ${deck.color}`}>{deck.icon}</span><b>{deck.title}</b><small>{cards.length} بطاقة</small></div><button type="button" className="select-deck" onClick={() => toggleDeck(deck.id)}>{allSelected ? "إلغاء الكل" : "اختيار الكل"}</button></header>{cards.map(card => <label className="select-card" key={card.id}><input type="checkbox" checked={selected.includes(card.id)} onChange={() => toggle(card.id)} /><span dir={dir(card.frontLanguage, card.front)}>{card.front}</span><small>{stateLabels[data.scheduling.find(schedule => schedule.cardId === card.id)?.state || "NEW"]}</small></label>)}</section>})}</div><button className="reveal custom-start" disabled={!selected.length} onClick={() => onStart(selected)}>ابدأ دراسة {selected.length || ""} بطاقة <span>←</span></button></Modal>
}
function streak(data: FlashyData) { const days = new Set(data.reviews.map(r => r.reviewedAt.slice(0, 10))); let count = 0, cursor = new Date(); if (!days.has(today())) cursor.setDate(cursor.getDate() - 1); while (days.has(cursor.toLocaleDateString("en-CA"))) { count++; cursor.setDate(cursor.getDate() - 1); } return count; }
